#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$command = new \Faby\PhpHelper\Command\PhpHelperCommand();
$application->add($command);
$application->setDefaultCommand($command->getName(), true);

$application->run();
